# Generated by Django 4.2.4 on 2023-08-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('designation', models.CharField(choices=[('JE', 'Junior Engineer'), ('ER', 'Engineer'), ('TL', 'Team Lead'), ('PM', 'Project Manager'), ('MG', 'Manager')], max_length=2)),
                ('mobile', models.BigIntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
